import React from "react";
import { useLocation } from "react-router-dom";
import "../styling/DiagnosisPage.css";

const DiagnosisPage = () => {
  // Retrieve the final diagnosis data (the analysis result) passed via navigate
  const location = useLocation();
  const { finalDiagnosis } = location.state || {};

  if (!finalDiagnosis) {
    return (
      <div className="diagnosis-container">
        <div className="diagnosis-card">
          <h2 className="diagnosis-title">No diagnosis available</h2>
        </div>
      </div>
    );
  }

  return (
    <div className="diagnosis-container">
      <div className="diagnosis-card">
        <div className="diagnosis-header">
          <h2 className="diagnosis-title">
            <span role="img" aria-label="medical-icon">🩺</span> Final Stress Analysis
          </h2>
          <p className="diagnosis-subtitle">
            Here is the analysis of your recorded session:
          </p>
        </div>

        {/* Display the analysis summary */}
        <div className="diagnosis-summary">
          <p className="summary-text">
            <span role="img" aria-label="summary-icon">💬</span> {finalDiagnosis.summary}
          </p>
        </div>

        {/* Optionally display additional diagnosis details if available */}
        {(finalDiagnosis.classification ||
          finalDiagnosis.likelihood ||
          finalDiagnosis.treatmentPlan ||
          finalDiagnosis.followUp ||
          finalDiagnosis.videoAnalysis) && (
          <ul className="diagnosis-list">
            {finalDiagnosis.classification && (
              <li>
                <strong>
                  <span role="img" aria-label="classification">🔖</span> Classification:
                </strong>{" "}
                {finalDiagnosis.classification}
              </li>
            )}
            {finalDiagnosis.likelihood && (
              <li>
                <strong>
                  <span role="img" aria-label="likelihood">🔮</span> Likelihood:
                </strong>{" "}
                {finalDiagnosis.likelihood}
              </li>
            )}
            {finalDiagnosis.treatmentPlan && (
              <li>
                <strong>
                  <span role="img" aria-label="treatment">💊</span> Treatment Plan:
                </strong>{" "}
                {finalDiagnosis.treatmentPlan}
              </li>
            )}
            {finalDiagnosis.followUp && (
              <li>
                <strong>
                  <span role="img" aria-label="follow-up">📅</span> Follow-Up:
                </strong>{" "}
                {finalDiagnosis.followUp}
              </li>
            )}
            {finalDiagnosis.videoAnalysis && (
              <li>
                <strong>
                  <span role="img" aria-label="video-analysis">📹</span> Video Analysis:
                </strong>{" "}
                {finalDiagnosis.videoAnalysis}
              </li>
            )}
          </ul>
        )}

        <div className="diagnosis-disclaimer">
          <p className="disclaimer-text">
            <strong>Disclaimer:</strong> The above analysis is generated by a language model and is provided for informational purposes only. It is not intended as a substitute for professional medical advice, diagnosis, or treatment. Always consult a licensed physician for any health concerns.
          </p>
        </div>
      </div>
    </div>
  );
};

export default DiagnosisPage;
