import React from "react";
import { useLocation } from "react-router-dom";
import "../styling/DiagnosisPage.css";

const DiagnosisPage = () => {
  // Retrieve the final diagnosis data passed via navigate
  const location = useLocation();
  const { finalDiagnosis } = location.state || {};

  if (!finalDiagnosis) {
    return (
      <div className="diagnosis-container">
        <div className="diagnosis-card">
          <h2 className="diagnosis-title">No diagnosis available</h2>
        </div>
      </div>
    );
  }

  return (
    <div className="diagnosis-container">
      <div className="diagnosis-card">
        <div className="diagnosis-header">
          <h2 className="diagnosis-title">
            <span role="img" aria-label="medical-icon">🩺</span> Final Diagnosis
          </h2>
          <p className="diagnosis-subtitle">
            Here is a summary of your medical analysis:
          </p>
        </div>
        {/* Disclaimer Section */}
        {/* <div className="diagnosis-disclaimer">
          <p className="disclaimer-text">
            <strong>Disclaimer:</strong> The above information is generated by a language model (LLM) and is provided for informational purposes only. It is not intended as a substitute for professional medical advice, diagnosis, or treatment. Always consult a licensed physician or other qualified health provider for any questions you may have regarding a medical condition.
          </p>
        </div> */}

        {/* Diagnosis Summary */}
        <div className="diagnosis-summary">
          <p className="summary-text">
            <span role="img" aria-label="summary-icon">💬</span> {finalDiagnosis.summary}
          </p>
        </div>

        {/* Diagnosis Details */}
        <ul className="diagnosis-list">
          <li>
            <strong><span role="img" aria-label="classification">🔖</span> Classification:</strong> {finalDiagnosis.classification}
          </li>
          <li>
            <strong><span role="img" aria-label="likelihood">🔮</span> Likelihood:</strong> {finalDiagnosis.likelihood}
          </li>
          <li>
            <strong><span role="img" aria-label="treatment">💊</span> Treatment Plan:</strong> {finalDiagnosis.treatmentPlan}
          </li>
          <li>
            <strong><span role="img" aria-label="follow-up">📅</span> Follow-Up Recommendations:</strong> {finalDiagnosis.followUp}
          </li>
        </ul>

        
        <div className="diagnosis-disclaimer">
          <p className="disclaimer-text">
            <strong>Disclaimer:</strong> The above information is generated by a language model (LLM) and is provided for informational purposes only. It is not intended as a substitute for professional medical advice, diagnosis, or treatment. Always consult a licensed physician or other qualified health provider for any questions you may have regarding a medical condition.
          </p>
        </div>
      </div>
    </div>
  );
};

export default DiagnosisPage;
